apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-client
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-client
  template:
    metadata:
      labels:
        app: flask-client
    spec:
      containers:
      - name: flask-client
        image: k3d-sample-registry.localhost:5001/flask-client:mtls
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: tls-certs
          mountPath: /app/tls
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: flask-client-tls

