apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-client
  template:
    metadata:
      labels:
        app: flask-client
    spec:
      containers:
        - name: flask-client
          image: flask-client:latest
          imagePullPolicy: Never

