apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-server-servicemonitor
  namespace: sample-app
  labels:
    release: kube-prometheus-stack
    app: flask-server
spec:
  namespaceSelector:
    matchNames: 
    - "sample-app"
  selector:
    matchLabels:
      app: flask-server
  endpoints:
    - port: flask-server-port
      path: /metrics
      interval: 30s
      scheme: https

      tlsConfig:
        serverName: flask-server
        ca:
          secret:
            name: flask-ca
            key: ca.crt
        cert:
          secret:
            name: flask-client-tls
            key: client.crt
        keySecret:
          name: flask-client-tls
          key: client.key
