apiVersion: v1
kind: Service
metadata:
  name: flask-server
  namespace: sample-app
  labels:
    app: flask-server
spec:
  selector:
    app: flask-server
  ports:
    - name: flask-server-port
      protocol: TCP
      port: 5000
      targetPort: 5000
